version: "3"
services:
  node:
    build:
      context: ./node
      dockerfile: Dockerfile
    image: luizortega/node
    container_name: node
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s node index.js
    networks:
      - nodenet
    depends_on:
      - db

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: luizortega/nginx
    container_name: nginx
    networks:
      - nodenet
    ports:
      - "8080:80"

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql/CreateDatabase.sql:/docker-entrypoint-initdb.d/CreateDatabase.sql
      - ./mysql/db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    networks:
      - nodenet

networks:
  nodenet:
    driver: bridge
